### ISSUE TITLE
Support for orange pi zero?

### ISSUE THREAD

**Issue by M0ebiu5** [alexreinert/piVCCU#11]
Is there a special reason why opi0 it is not supported?

**Comment by alexreinert** [comment]
The OPi Zero has only 256MB RAM and only a H2+ CPU, but is not that much cheaper than a OPi One.
Because of that I do not want to spend money for a test device.
But if someone donates a test device, I can add support, too. (Same for the other OPi models supported by Armbian.)

**Comment by M0ebiu5** [comment]
The zero is also available with 512MB RAM and the H2+ SOC is a H3 without hdmi and gigabit network interface - so there is a good chance, that piVCCU works on this board (if the 26pin expansion port has the pins on the right location).

Maybe you could loosen the board checks and replace the error message with a warning, if the board is untesteted, but continue the installation?

**Comment by alexreinert** [comment]
It is not that easy: There must be a working device tree, so that the driver is loaded for the correct uart and reset GPIO pin. With a loosened check it would be possible, that a incompatbile DTO is loaded, which could prevent the board from working and booting. Even if it is very unlikely it could destroy the hardware, too.

I had a look at the Device Tree of the OPi Zero, that should be compatible with the current piVCCU drivers. But the GPIO pinout is slightly different. (UART1 instead UART3, PA07 instead PD14 for the reset PIN).

I'm pretty sure, that I could add support for the Zero, but for that, I need a test device. And as the OPi one is much the same price as the Zero but with a lot more power, I'm not willing to spend my money for a test device.

**Comment by M0ebiu5** [comment]
ic...thanks for the info!
If you are located in Austria, i could send you one of my boards.

**Comment by alexreinert** [comment]
Nope, germany.

**Comment by M0ebiu5** [comment]
Great, thanks!

**Comment by alexreinert** [comment]
I comitted the new device tree overlay and pushed the deb packages to the testing repository.
The image is baking at the moment, I will upload it in a couple of minutes

**Comment by M0ebiu5** [comment]
Cool, will try it asap!

**Comment by alexreinert** [comment]
The image is now available for download.

**Comment by alexreinert** [comment]
Released in stable -> Closed
