### ISSUE TITLE
run piVCCU on local network

### ISSUE THREAD

**Issue by tiegs** [alexreinert/piVCCU#250]
Hi Alex,

I'd like to run piVCCU on a local network. I plan to run openhab and pivccu on the same host.

As openhab does not support authentication against the CCU. I'd like to protect it and therefore run in on localhost/on internal network.

Is this be supported? And how would I archive this?
I guess changing the networking settings in /etc/piVCCU3/lxc.config would do the trick? Or is there anything else involved?
To be honest I have to idea how lxc bridging works. Would be greatly appreciated if you could point me in the right direction.

Thanks,
Til

**Comment by alexreinert** [comment]
In theory this is possible. But inside the CCU an internet connection is mandatory for several cases, so the usage without internet access of the CCU should be avoided.

**Comment by alexreinert** [comment]
Can this be closed?

**Comment by tiegs** [comment]
Sorry for my late reply. Yes this issue can be closed. Thanks.

**Comment by dicer** [comment]
@alexreinert Could you elaborate why internet access is required?
I guess device firmware updates are a problem otherwise. And HMIP devices require you to enter the key instead of using the keyserver. What else am I missing?

One could run the lxc container in NAT mode if openHAB is run on the same host and no other access from the LAN is needed, right? 

I for one use ssh to connect to the webui and also configured my pivccu to not be reachable on the LAN. I did not connect the bridge to eth0: `bridge_ports none` in /etc/network/interfaces
Besides the CCU complaining about no internet access (which can be faked by modifying /var/lib/piVCCU3/rootfs/bin/checkInternet ) everything seems to work ok for now.
