### ISSUE TITLE
Support Odroid C2

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/piVCCU#6]
Test device is needed first. Needs some more donations and availability of devices, currently they are out of stock everywhere.

**Comment by alexreinert** [comment]
Some news: I have now a test device. The UART hardware is a amlogic-meson which is not supported by kernel modules right now. I'm already porting the driver to this hardware, but it will take some time because the chip is not well documented :-(

**Comment by alexreinert** [comment]
I got the UART running but right now the code looks more like prove-of-concept, than on real production code.
And I have to deal with the device tree overlay, right now it was just done by hand and this needs to be included in the packages.
And the last point I have to deal with is, that the C2 is arm64 and not armhf, so I need to figure out a way to package pivccu for two platforms without to maintain two different packages.

So it will take some more time, but I'm now sure, that I can support the C2.

**Comment by Jojo-A** [comment]
Hi,

I really like your project! It looks as the most promising solution for what I like to do.

Actually I am running my main home automation system on an ODROID C1, while my CCU2 is running on a RPi0. This is obviously a huge waste of silicon, because both devices are massively bored with what they are doing ;) .
So I am looking forward to see your project supporting ODROID-C-series SBCs! Although I can not help in driver programming directly, I am willing to perform some tests and try to port your stuff to the C1, if you can tell me how.

Do I get it right, that there will be hardware-support for the HM-MOD-RPI-PCB on other hardware platform than RPi? From what I've read until now, all project required strictly the RPi as base platform for the HM-MOD-RPI-PCB.

Cheers

**Comment by alexreinert** [comment]
I already support the HM-MOD-RPI-PCB on different hardware platforms (RPi, Tinkerboard, several OPi). C2 is currently in development.
The C1 should be possible after that, as far as I saw it, the used UART is mostly the same as on the C2.

**Comment by leonsio** [comment]
If you want to use homematic ip you need a Kernel driver like pivccu. 
Hm-mod-Pcb can run without kernel Module in homematic Mode. You need only to passtrough the device to the YAHM lxc and then make some Changes on rfd.conf

Von meinem iPhone gesendet

**Comment by alexreinert** [comment]
Odroid C2 support is mostly finished, only testing is pending.
I hope to release it this week

**Comment by alexreinert** [comment]
Released in testing

**Comment by Jojo-A** [comment]
Thanks a lot!
I'll give it a try, in case of any issues, I will report back.

**Comment by alexreinert** [comment]
@Jojo-A can you please contact me in private (alex (at) areinert (dot) de), maybe you can help me with some questions regarding the C1.

**Comment by alexreinert** [comment]
Released in stable
