### ISSUE TITLE
superfluous installation restrictions in pre- and hard exits on config failure in post-inst scripts

### ISSUE THREAD

**Issue by Koebnick** [alexreinert/piVCCU#64]
Hi !

I just switched from a super old lxccu to pivccu and it works fine for me.
Problem is: I have it all running on a cubieboard4 ... had to configure and compile an own kernel for getting all that veth req's for lxc avail (ready-to-use-kernels for that board are really crabby ... nothing works as expected).
As for installing PIVCCU, I had to cheat a lot in the installation pre- and post scripts just because the existing ones request stuff, that is not really neccessary.
Sounds queer, but this unneccessary stuff is the CCU2 hardware and emulation libs.
I do not have the eq3 sandwich, I just have a EQ3 Lan GW somewhere plugged in.
The complete PIVCCU just runs great ... only complaining about some components (of the ccu2) that do not work. Well, they are just not there and don't need to be ;-)
My complete system consists of one CB4, one Lan-GW, about 50 Radio HM-components and it runs fine.

So please, Alex, take those pre req checks and hard exits in case of config failure in post inst out of the scripts or give some options for overriding them. You will have masses of users in addition because currently you are depending on PI and sandwich, but without them, you just depend on a working lxc and bridging device. Maybe there'll be a way to get rid of the (HM CCU WebFrontend's) warnings "hardware not functioning" for those end users, that are puzzelt by them (ignoring, that they have a firmware running without the hardware ... indeed, they shouldn't be puzzelt).

rest: great job !
^5
sven

**Comment by alexreinert** [comment]
Hi,

I will not do that for piVCCU. One goal of piVCCU is to emulate the CCU as much as possible and this causes some restrictions as you described. But this is intended.

Maybe I could get more users without this strict goal, but a lot of the current users like piVCCU because of that strict goal.

The assumption, that I depend on Pi and the RF module is wrong. There are several other SBCs supported and I have a software emulation of the RF module. So inside the container, it will look like there is a RF module, but you do not need the physical hardware for it. Using that software emulation and a LAN-GW you can install on more ore less all SBCs with a recent kernel (at least 4.4 is required).
(This works even without the LAN-GW, but working without any RF hardware makes no real sense ;-) )

At the moment I'm working on an other project with the approch to install the Homematic software without the LXC emulation and with a lot more flexibility. Maybe this would be the right solution for you.

Alex
