### ISSUE TITLE
How to start piVCCU without BidCos Hardware

### ISSUE THREAD

**Issue by Harald-B-Rupp** [alexreinert/piVCCU#8]
Hi Alex, i have several external Antennas and dont use an Hardware Board attached to an Raspi, how could i disable the search for the additional BidCos Hardeware Module, becasue the PIVCCU needs a long time to start, because it will not detect the Hardware Board.

Thanks for an Tip

Harald

**Comment by alexreinert** [comment]
Hi Harald, 
currently there is no solution for that, piVCCU requires a Homematic radio module to work, because I want to be as compatible as possible to the original CCU2.
Maybe I will write a fake driver to support running piVCCU without a radio module, but there are no concrete plans for that at the moment.
Alex

**Comment by Harald-B-Rupp** [comment]
Thanks Alex!
